apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  progressDeadlineSeconds: 600

  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: dummylearner/capstone:V1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
