apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels: 
      app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
