Description: >
  Capstone Project
  Creates two EC2 instance

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: capstone
    Type: String
  SSHKeyName:
    Description: SSH key for management access
    Default: capstone
    Type: String
  amiImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-0149b2da6ceec4bb0
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: capstone-management-SG
      GroupDescription: Allow port 22 for management
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: capstone
      ImageId: ami-0149b2da6ceec4bb0
      Tags:
        - Key: Name
          Value: capstone-EC2Instance1
        - Key: Project
          Value: capstone

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: capstone
      ImageId: ami-0149b2da6ceec4bb0
      Tags:
        - Key: Name
          Value: capstone-EC2Instance2
        - Key: Project
          Value: capstone
